name: EC2 Deploy
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Launch EC2 Instance
        id: launch-ec2
        run: |
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ${{ vars.IMAGE_ID }} \
            --count 1 \
            --instance-type t2.micro \
            --key-name ${{ vars.KEY_NAME }} \
            --security-group-ids ${{ vars.SECURITY_GROUP_ID }} \
            --subnet-id ${{ secrets.SUBNET_ID }} \
            --query 'Instances[0].InstanceId' \
            --output text)
          
          aws ec2 wait instance-running --instance-ids $INSTANCE_ID
          
          echo "instance_id=$INSTANCE_ID" >> $GITHUB_OUTPUT

      - name: Create Custom AMI
        run: |
          aws ec2 create-image \
            --instance-id ${{ steps.launch-ec2.outputs.instance_id }} \
            --name "github-actions-cursodevops-$(date +%Y%m%d-%H%M%S)" \
            --description "AMI creada usando GitHub Actions"
